#!/bin/bash

test_file=$1
./build/ive "$test_file" -emit=mlir 2>&1 | \
  $LLVM_SRC/mlir/utils/generate-test-checks.py \
  --source "$test_file" \
  --source_delim_regex='def ' \
  --check-prefix='CHECK' \
  -i

# Convert // CHECK* to # CHECK* and // NOTE to # NOTE
sed -i \
  -e 's|^// CHECK|# CHECK|g' \
  -e 's|^// CHECK-|# CHECK-|g' \
  -e 's|^// NOTE:|# NOTE:|g' \
  "$test_file"

# Remove the autogenerated guidance block
sed -i '/^\/\/ This script is intended to make adding checks/,/^\/\/   \* https:\/\/mlir\.llvm\.org\/getting_started\/TestingGuide\/$/d' "$test_file"

# Collapse multiple blank lines to a single blank line
sed -i ':a;N;$!ba;s/\n\{3,\}/\n\n/g' "$test_file"

# Remove blank line after NOTE only
sed -i \
  -e '/^# NOTE:/{n;/^$/d;}' \
  "$test_file"

# Ensure exactly one blank line after RUN
sed -i \
  -e '/^# RUN:/{n;/^$/!s/^/\n/;}' \
  "$test_file"

echo "Generated checks in $test_file"
